name: run shell commands 
on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run shell commands
      run: |
        echo "Hello World"